config/routes.rb
Rails.application.routes.draw do
  

  get 'activities/index'

  resources :activities
  devise_for :users,:controllers => { :registrations => "user/registrations"}

  #devise_scope :user do
   #get "Sign up", to: "devise/registrations#new"
   #get "Log in", to: "devise/sessions#new"
   #get "Log out", to: "devise/sessions#destroy"
   #match '/sessions.user', to: 'devise/sessions#create' , via: :post
  #end
  get 'list_bookings', to: 'bookings#list'
  resources :bookings, only: [:create, :destroy]
  get 'search_bookings', to: 'bookings#search'
  get 'search_store_bikes', to: 'store_bikes#search'
 # get 'welcome/index'
 # get 'search_store_bikes', to: 'storebikes#search'
  resources :welcome
  resources :friendships
  root to: 'welcome#index' 

  get 'my_profile', to: 'users#my_profile'
  resources :users, only: [:show]
  resources :bikes do
   member do
    put 'like' => 'bikes#upvote'
    put 'unlike' => 'bikes#downvote'
   end 
  end 
  resources :store_bikes
  resources :pages
  get 'my_friends', to: 'users#my_friends'
	 get 'search_friends', to: 'users#search'
  resources :stores do  
   resources :store_bikes do  
     resources :bookings  
    end  
  end
 post 'add_friend', to: 'users#add_friend'
 resources :user_bookings, only: [:create, :destroy]
  
 get '/search' => 'pages#search', :as => 'search_page'
 match '*path', via: :all, to: redirect('/404')
end

app/models/store.rb
class Store < ActiveRecord::Base
    
    has_many :bikes, :through => :store_bikes
    has_many :store_bikes, :dependent => :destroy
    mount_uploader :image, ImageUploader
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  #before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name,:image, :remove_image)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %><br><br>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1 class="title">Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<!--p id="notice"><!%= notice %></p-->

<!DOCTYPE html>
<html lang='en'>

<h1 class="title">CycleHub Stores</h1>

  <% @stores.each do |store| %>
  
    <!--div class="col-sm-6 col-md-4">
      <div class="thumbnail thumb-box">
        <h2 style="text-align:center;"><!%= store.name %></h2>
          <!%= image_tag(store.image, size: "250x300") %>
            <div class="caption" style="text-align:center;">
            </div>
          <!% end %-->
          
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
              <div class="well well-lg">
                <div class="store-name">
                  <h2><%= store.name %></h2>
                    <%= link_to 'Store Bikes', store_store_bikes_path(store) %>
                    <% if signed_in? && (current_user.admin?) %>
                      <%= link_to 'Edit', edit_store_path(store) %>
                      <%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
   <% if signed_in? && (current_user.admin?) %>
     <%= link_to 'New Store', new_store_path %>
   <% end %>

</html>

app/views/stores/new.html.erb
<h1 class="title">New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
  <strong>Image:</strong-->
  <%= image_tag @store.image%>
</p>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>