config/routes.rb
Rails.application.routes.draw do
  

  get 'activities/index'

  resources :activities
  devise_for :users,:controllers => { :registrations => "user/registrations"}

  #devise_scope :user do
   #get "Sign up", to: "devise/registrations#new"
   #get "Log in", to: "devise/sessions#new"
   #get "Log out", to: "devise/sessions#destroy"
   #match '/sessions.user', to: 'devise/sessions#create' , via: :post
  #end
  get 'list_bookings', to: 'bookings#list'
  resources :bookings, only: [:create, :destroy]
  get 'search_bookings', to: 'bookings#search'
  get 'search_store_bikes', to: 'store_bikes#search'
 # get 'welcome/index'
 # get 'search_store_bikes', to: 'storebikes#search'
  resources :welcome
  resources :friendships
  root to: 'welcome#index' 

  get 'my_profile', to: 'users#my_profile'
  resources :users, only: [:show]
  resources :bikes do
   member do
    put 'like' => 'bikes#upvote'
    put 'unlike' => 'bikes#downvote'
   end 
  end 
  resources :store_bikes
  resources :pages
  get 'my_friends', to: 'users#my_friends'
	 get 'search_friends', to: 'users#search'
  resources :stores do  
   resources :store_bikes do  
     resources :bookings  
    end  
  end
 post 'add_friend', to: 'users#add_friend'
 resources :user_bookings, only: [:create, :destroy]
  
 get '/search' => 'pages#search', :as => 'search_page'
 match '*path', via: :all, to: redirect('/404')
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :bookings, dependent: :destroy
  has_many :store_bikes, through: :bookings
  has_many :friendships
  has_many :activities
  has_many :friends, through: :friendships
  acts_as_voter
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { self.email = email.downcase }
 # validates :username, presence: true,
 # uniqueness: { case_sensitive: false },
  #length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
  uniqueness: { case_sensitive: false },
  format: { with: VALID_EMAIL_REGEX }
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end 
  
  def under_store_bike_limit?
    (bookings.count < 2)
  end
  
  def can_add_store_bike?(id)
    under_store_bike_limit? && !store_bike_already_added?(id)
  end
  
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
  
  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param)+last_name_matches(param)+email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end 
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :last_name])
        devise_parameter_sanitizer.permit(:account_update, keys:[:first_name, :last_name])
        
    end
    
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
    
    def index
        @bookings = Booking.all
    end
    
    def my_profile 
        @user = current_user
        @bookings = current_user.bookings
    end 
    
    def show
        @user = User.find(params[:id])
     #   @user = current_user
       # redirect_to :action => :my_profile
       @bookings = @user.bookings
    end
    
    def add_friend
        @friend = User.find(params[:friend])
        current_user.friendships.build(friend_id: @friend.id)
        
        if current_user.save
            flash[:success] = "Friend was successfully added"
        else
            flash[:danger] = "There was something wrong with the friend request"
        end
        redirect_to my_friends_path
    end 
    
    def my_friends
        @friendships = current_user.friends
    end
    
    
    
    def search
        if params[:search_param].blank?
            flash.now[:danger]="You have entered an empty search"
        else
            @users = User.search(params[:search_param])
            @users = current_user.except_current_user(@users)
            flash.now[:danger] = "No users match this search criteria" if @users.blank?
        end 
        render partial: 'friends/result'    
        end 
    
end 

app/helpers/user_helper.rb
module UserHelper
    
   # def avatar_url(user)
    #    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
            #gravatar_url = "#{root_url}images/guest.png"
            #gravatar_id = user.id
            #size = options[:size]
            #gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
     #       "http://gravatar.com/avatar/#{gravatar_id}.png"
            #image_tag(gravatar_url, alt: user.id, class: "img-circle")
#    end
    
    
    def gravatar_for(user, options = { :size => 50})
        if user.email?
            gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
            size = options[:size]
            gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
            image_tag(gravatar_url, alt: user.full_name, class: "img-circle")
        else
            image_tag("/img/avatar_default.png", alt: user.full_name, class: "gravatar")
        end
    end 
end

app/views/users/_result.html.erb
<div class="results-block">
  <%= bootstrap_flash %>
</div>

<% if @storebike %>
  <div class="well results-block">
    
      <td>Bike:<%= @storebike.id %></td>
      <td>Name:<%= @storebike.bike.name%></td>
      <td>Store:<%= @storebike.store.name%></td>
      <td>Price:<%= @storebike.bike.price%></td>
   
  </div>
<% end %>

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>

<% if @friendships.size > 0 %>
 <div class="container vertical-center">
  <div class="col-md-12 col-md-offset-0">
    <table class="table table-striped">
      <thead>
        <tr>
            <th colspan = "6" class="page-header">
                <h2>My Friends</h2>
            </th>
        </tr>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friendships.each do |friend| %>
          <tr>
            <td><%= friend.full_name %></td>
            <td><%= friend.email %></td>
            <td>
                <%= link_to "View Profile", user_path(friend), class:"btn btn-primary btn-xs" %>
                <%= link_to "Remove Friend", friendship_path(friend), 
                          method: :delete,
                          data: {confirm: "Are you sure?"}, 
                          class: "btn btn-xs btn-danger" %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
    <div class="row col-lg-12">
        <p class = "lead">You dont have any friends yet</p>
    </div>
    </div>
    </div>
<% end %>

app/views/users/my_profile.html.erb
<% @user ||= current_user %>
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div class="jumbotron">
      <div class="container vertical-center">
        <div class="col-md-6 col-md-offset-3">
          <h1 align="center"> <%= gravatar_for(current_user, size: 300) %> </h1>
          <strong>Welcome <%= current_user.first_name %></strong>
        </div>
    </div>
    <div class="container vertical-center">
      <div class="col-md-6 col-md-offset-3">
        <%= link_to 'Browse Bikes', bikes_path, class: 'btn btn-lg btn-info'%>
      </div>
    </div>
    <div class="container vertical-center">
      <div class="col-md-6 col-md-offset-3">
        <div id="storebike-lookup">
          <%= form_tag search_store_bikes_path, remote: true, method: :get, id: "storebike-lookup-form" do %>
            <div class="form-group row no-padding text-center col-md-12">
                <%= number_field_tag :storebike, params[:storebike], placeholder: "Bike id", autofocus: true, class: "form-control search-box input-md" %>
            </div>
            <div class="container vertical-center">
              <div class="col-md-6 col-md-offset-3">
                <%= button_tag(type: :submit, class: "btn btn-sm btn-success") do %>
                  <i class="fa fa-search"></i> Look up a bike
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <div class="container vertical-center">
    <div class="col-md-10 col-md-offset-1">
      <div id="results">
        <%= render "users/result" %>
      </div>
    </div>
  </div>
  <div class="container vertical-center">
    <div class="col-md-12 col-md-offset-0">
      <%= render 'store_bikes/list' %>
    </div>
  </div>
</div>

</html>


 

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    <div class="col-md-6 no-padding">
      <%= f.input :first_name, required: true, autofocus: true %>
    </div>
    <div class="col-md-6 no-padding left-padding">
      <%= f.input :last_name, required: true, autofocus: true %>
    </div>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/users/show.html.erb
<h1 class = "title">User Details</h1>

<dl class="dl-horizontal">
    
    <dt><strong>Full Name</strong></dt>
    <dd><%= @user.full_name %></dd><br>
    <dt><strong>Email</strong></dt>
    <dd><%= @user.email %></dd><br>
 
    <dd><%= gravatar_for(@user, size: 300) %></dd>
</dl>


<% if @user.bookings.size > 0 %>
    <%= render 'store_bikes/list' %>
<% else %>
    <p class="lead">This user currenty has no bookings</p>
<% end %>

<%= link_to "Back", my_friends_path, class: "btn btn-primary" %>