config/routes.rb
Rails.application.routes.draw do
  

  get 'activities/index'

  resources :activities
  devise_for :users,:controllers => { :registrations => "user/registrations"}

  #devise_scope :user do
   #get "Sign up", to: "devise/registrations#new"
   #get "Log in", to: "devise/sessions#new"
   #get "Log out", to: "devise/sessions#destroy"
   #match '/sessions.user', to: 'devise/sessions#create' , via: :post
  #end
  get 'list_bookings', to: 'bookings#list'
  resources :bookings, only: [:create, :destroy]
  get 'search_bookings', to: 'bookings#search'
  get 'search_store_bikes', to: 'store_bikes#search'
 # get 'welcome/index'
 # get 'search_store_bikes', to: 'storebikes#search'
  resources :welcome
  resources :friendships
  root to: 'welcome#index' 

  get 'my_profile', to: 'users#my_profile'
  resources :users, only: [:show]
  resources :bikes do
   member do
    put 'like' => 'bikes#upvote'
    put 'unlike' => 'bikes#downvote'
   end 
  end 
  resources :store_bikes
  resources :pages
  get 'my_friends', to: 'users#my_friends'
	 get 'search_friends', to: 'users#search'
  resources :stores do  
   resources :store_bikes do  
     resources :bookings  
    end  
  end
 post 'add_friend', to: 'users#add_friend'
 resources :user_bookings, only: [:create, :destroy]
  
 get '/search' => 'pages#search', :as => 'search_page'
 match '*path', via: :all, to: redirect('/404')
end

app/models/bike.rb
class Bike < ActiveRecord::Base
    
    validates :name, presence: true, uniqueness: true  
    #has_many :stores, :through => :store_bikes  
    has_many :stores, :through => :store_bikes  
    has_many :bikes, :through => :store_bikes  
    has_many :store_bikes, :dependent => :destroy
    has_many :bookings, through: :store_bikes
    acts_as_votable
    mount_uploader :image, ImageUploader
  
  
    def self.search(search)  
        where("lower(stores.name) LIKE :search OR lower(bikes.name) LIKE :search", search: "%#{search.downcase}%").uniq   
    end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:create, :show, :edit, :update, :destroy, :upvote, :downvote]
  #before_action :authenticate_user!, :except => [:show, :index]
  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all.order(:cached_votes_score => :desc)
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end
  
  def list
    @bookings = @user.bookings.all if @user
  end 
  
  
  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bike }
      else
        format.html { render action: 'new' }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @bike.upvote_from current_user
    redirect_to bikes_path
  end 

  def downvote
    @bike.downvote_from current_user
    redirect_to bikes_path
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:name, :image, :remove_image, :price)
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_form.html.erb
<!DOCTYPE html>
<html lang='en'>


<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>
    <%= f.label :price %><br>
    <%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), :step => 0.01 %><br><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</html>

app/views/bikes/edit.html.erb
<!DOCTYPE html>
<html lang='en'>


<h1 class="title">Editing Bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>
</html>

app/views/bikes/index.html.erb
<!DOCTYPE html>
<html lang='en'>

<h1 class="title">Bikes for Rent</h1>
        
<header>
 <% if signed_in? && (current_user.admin?) %>
    <td><h3> <%= link_to 'New Bike', new_bike_path %> </h3></td>
<% end %>
</header>
  <% @bikes.each do |bike| %>
  
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail thumb-box">
        <h2 style="text-align:center;"><%= bike.name %></h2>
        <%= image_tag(bike.image, size: "250x300") %>
        <h5 style="text-align:center;"><%= bike.price %></h2>
        <div class="caption" style="text-align:center;">
          
          <%= link_to like_bike_path(bike), class: 'like', method: :put do %>
          <button type="button" class="btn btn-info" aria-label = "Left align">
            <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
            <span class="badge"><%= bike.get_upvotes.size %></span>
          </button>
          <% end %>
          
          <%= link_to unlike_bike_path(bike), class: 'like', method: :put do %>
          <button type="button" class="btn btn-info" aria-label = "Left align">
            <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
            <span class="badge"><%= bike.get_downvotes.size %></span>
          </button>
        <br>
        <!--td><%= link_to 'Show', @bike %> </td><br-->
          <% if signed_in? && (current_user.admin?) %>
            <td><%= link_to 'Edit', edit_bike_path(bike) %></td><br>
            <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
   
  
  <% end %>
  </html>
  

app/views/bikes/new.html.erb
<!DOCTYPE html>
<html lang='en'>


<h1 class="title">New Bike</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>
</html>

app/views/bikes/show.html.erb
<!DOCTYPE html>
<html lang='en'>


<p id="notice"><%= notice %></p>

<p>
  <span>Name:</span>
  <span><strong><%= @bike.name %></strong></span>
  <span><strong>Price:</strong></span>
  <span><%= @bike.price%></span>
</p>
<div class="photo">
  <%= image_tag @bike.image%>
</div>

  <%= link_to 'Edit', edit_bike_path(@bike) %> |
  <%= link_to 'Back', bikes_path %>
</html>