config/routes.rb
Rails.application.routes.draw do
  

  get 'activities/index'

  resources :activities
  devise_for :users,:controllers => { :registrations => "user/registrations"}

  #devise_scope :user do
   #get "Sign up", to: "devise/registrations#new"
   #get "Log in", to: "devise/sessions#new"
   #get "Log out", to: "devise/sessions#destroy"
   #match '/sessions.user', to: 'devise/sessions#create' , via: :post
  #end
  get 'list_bookings', to: 'bookings#list'
  resources :bookings, only: [:create, :destroy]
  get 'search_bookings', to: 'bookings#search'
  get 'search_store_bikes', to: 'store_bikes#search'
 # get 'welcome/index'
 # get 'search_store_bikes', to: 'storebikes#search'
  resources :welcome
  resources :friendships
  root to: 'welcome#index' 

  get 'my_profile', to: 'users#my_profile'
  resources :users, only: [:show]
  resources :bikes do
   member do
    put 'like' => 'bikes#upvote'
    put 'unlike' => 'bikes#downvote'
   end 
  end 
  resources :store_bikes
  resources :pages
  get 'my_friends', to: 'users#my_friends'
	 get 'search_friends', to: 'users#search'
  resources :stores do  
   resources :store_bikes do  
     resources :bookings  
    end  
  end
 post 'add_friend', to: 'users#add_friend'
 resources :user_bookings, only: [:create, :destroy]
  
 get '/search' => 'pages#search', :as => 'search_page'
 match '*path', via: :all, to: redirect('/404')
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="span3">
                <div class="footer-widget">
                    <h2 class="brand widget-title">CycleHub</h2>
                    <p class="footer-tag-line">Managing Your Cycling</p>
                            <p>04293356431</p>
                    </li>
                </div>
            </div>
        </div>
        
    </div>
    
</footer>

app/views/layouts/_header.html.erb
<!--link href='https://fonts.googleapis.com/css?family=Bungee' rel='stylesheet' type='text/css'-->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <%= link_to image_tag("logo.png", alt: "logo", width: '70px'), '/', class: 'navbar-brand' %>
      <%= link_to 'CycleHub', root_path, class: "navbar-brand" %>
    </div>
      
    <% if current_user %>
   
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'My Profile', my_profile_path%></li>
        <li class="active"><%= link_to "Edit Profile", edit_registration_path(current_user) %></li>
        <li class="active"><%= link_to "Rent a Bike", stores_path %></li>
        <li class="active"><%= link_to "Recent Activities", activities_path %></li>
        <li class="active"><%= link_to "My Friends", my_friends_path %></li>
      </ul>
  
     
        <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>  
          <div class="input-group">  
            <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
            <div class="input-group-btn">  
              <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
            </div>  
          </div>  
       

      <ul class="nav navbar-nav navbar-right col-md-5">
        <li class="col-md-8 user-name text-right">
          <i class="fa fa-user"></i>
            <%= current_user.first_name.present? ? current_user.first_name : current_user.email %>
        </li>
        <%= link_to new_user_registration_path, class: 'btn btn-info sign-up' do %><i class="glyphicon glyphicon-user"></i>Sign Up <% end %>
       
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-default log-out' do %><i class="glyphicon glyphicon-sign-out"></i>Log Out <% end %>
        <% else %>
          <%= link_to new_user_session_path,  class: 'btn btn-default log-in' do %><i class="glyphicon glyphicon-sign-in"></i>Log In <% end %>
        <% end %>
        
      </ul>
       <% end %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>


<head>

  <link href='https://fonts.googleapis.com/css?family=Bungee' rel='stylesheet' type='text/css'>
  <title>Cycle Hub</title>
  <%= stylesheet_link_tag    'application',  media: 'all', 'data-turbolinks-track': 'load' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'load' %>
  <%= csrf_meta_tags %>

  
  <link rel= "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link rel= "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.js"></script>
  
</head>
<% unless controller_name == "welcome" %>
<%= render 'layouts/header' %>
<% end %>
  <body>
    <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>